-- the second script that will be run by Ninja's migration engine script
create table User_data_followers (
    User_data_id int8 not null,
    followers int8
);
create table User_data_following (
    User_data_id int8 not null,
    following int8
);
create table User_data_post (
    User_data_id int8 not null,
    post_id int8
);
create table Post (
	id int8 generated by default as identity,
	subtitle varchar(500),
	image varchar(500),
	content varchar(500),
	postedAt timestamp,
	primary key(id)
	
);